# what is numpy ?

- num = numeric
- py = python

- numpy is scientific computing library for python
- Support large number of data in the form of multi- dimensional array and matrix
- use for mathematic calculation like linear algebra,random number capabilites



In [ ]:
pip install numpy

In [ ]:
import numpy as np

# 1d array



In [ ]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [ ]:
type(arr_1d)

numpy.ndarray

In [ ]:
print('Dimentions of array :',arr_1d.ndim)

Dimentions of array : 1


#2D array


In [ ]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print('Dimension of array :',arr_2d.ndim)

Dimension of array : 2


In [ ]:
arr_1d.size

4

In [ ]:
arr_2d.shape  #row and columns

(2, 4)

In [ ]:
arr_1d.dtype

dtype('int64')

In [ ]:
arr_2d.dtype

dtype('int64')

In [ ]:
mx_1s = np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
ar_1d = np.ones(5)
print(ar_1d)

[1. 1. 1. 1. 1.]


In [ ]:
ar_1s = np.ones(5, dtype = int)
print(ar_1s)

[1 1 1 1 1]


In [ ]:
ar_0s = np.zeros(5)
print(ar_0s)

[0. 0. 0. 0. 0.]


In [ ]:
# np.empty

#Numpy functions

In [ ]:
#arange()

#np.arange(start, end, steps)
ar_1d = np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
even_ar = np.arange(1,13,2)
print(even_ar)

[ 1  3  5  7  9 11]


In [ ]:
#linspace()
np.linspace(1,5,4)


array([1.        , 2.33333333, 3.66666667, 5.        ])

In [ ]:
#reshape()

ar_2d = ar_1d.reshape(3,4)
print(ar_2d)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
ar_3d = ar_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
#ravel()

ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#flatten()
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#transpose() - ro to column colume to row

ar.transpose()


array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [ ]:
#mathematical
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)

print(arr1)
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
np.dot(arr1,arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
arr1.max()

np.int64(9)

In [ ]:
arr1.argmax() #max index

np.int64(8)

In [ ]:
arr1.max(axis = 0)

array([7, 8, 9])

In [ ]:
arr1.max(axis = 1)

array([3, 6, 9])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1.min()

np.int64(1)

In [ ]:
arr1.argmin()

np.int64(0)

In [ ]:
arr1.min(axis = 1)

array([1, 4, 7])

In [ ]:
np.sum(arr1)

np.int64(45)

In [ ]:
np.sum(arr1, axis = 0)

array([12, 15, 18])

In [ ]:
np.mean(arr1)

np.float64(5.0)

In [ ]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [ ]:
np.std(arr1)

np.float64(2.581988897471611)

In [ ]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [ ]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [ ]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [ ]:
#slicing

In [ ]:
mx = np.arange(1,101).reshape(10,10)
print(mx)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [ ]:
mx[0] #row

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
mx[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
mx[2]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
mx[0,1]

np.int64(2)

In [ ]:
mx[1][0]

np.int64(11)

In [ ]:
mx[0][1]

np.int64(2)

In [ ]:
mx[0,0].ndim

0

In [ ]:
mx[:,0] #all row, 0th row  #column

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
mx[:,0].ndim

1

In [ ]:
mx[:, 0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [ ]:
mx[:,0:1].ndim

2

In [ ]:
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
mx[1:5, 0:5]

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]])

In [ ]:
mx[1:4, 1:4]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [ ]:
mx[:,1:3]

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

In [ ]:
mx[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
mx[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
mx[:, 0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [ ]:
mx.itemsize # 8 bite

8

In [ ]:
mx.dtype

dtype('int64')

In [ ]:
#concatination

In [ ]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)
arr2 = np.arange(17,33).reshape(4,4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
list_1 = [1,2,3,4]
list_2 = [5,6,7,8]

In [ ]:
list_1 + list_2

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
arr1 + arr2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [ ]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [ ]:
# row vise
np.concatenate((arr1,arr2), axis = 1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [ ]:
# stack v - vertical, h - horisontal

np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [ ]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [ ]:
np.vstack((arr1,arr1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.split(arr1,2) #equal split value

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [ ]:
np.split(arr1, 2, axis = 1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [ ]:
list_1 = np.split(arr1,2)
print(list_1)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [ ]:
type(list_1)

list

In [ ]:
list_1[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
list_1[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
type(list_1[0])

numpy.ndarray

In [ ]:
data1 = np.array([1,3,4,5])
print(data1)

[1 3 4 5]


In [ ]:
np.split(data1, [1,3]) # before 1 value , before 3 values, rest of

[array([1]), array([3, 4]), array([5])]

In [ ]:
#finding Trignometry

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
np.sin(180)

np.float64(-0.8011526357338304)

In [ ]:
np.sin(60)

np.float64(-0.3048106211022167)

In [ ]:
np.sin(90)

np.float64(0.8939966636005579)

In [ ]:
np.cos(180)

np.float64(-0.5984600690578581)

In [ ]:
np.cos(90)

np.float64(-0.4480736161291701)

In [ ]:
np.tan(180)

np.float64(1.3386902103511544)

In [ ]:
# string oprations

In [ ]:
char_name = 'swaraj'
str_1 = 'hello there'

In [ ]:
np.char.add(char_name,str_1)

np.str_('swarajhello there')

In [ ]:
np.char.upper(char_name)

array('SWARAJ', dtype='<U6')

In [ ]:
np.char.center(str_1, 60, fillchar = '*')

array('************************hello there*************************',
      dtype='<U60')

In [ ]:
np.char.split(str_1)

array(list(['hello', 'there']), dtype=object)

In [ ]:
np.char.splitlines('hello\npython')

array(list(['hello', 'python']), dtype=object)

In [ ]:
str1 = 'dmy'
str2 = 'DMY'

In [ ]:
np.char.join([(':','/')],[str1,str2])

array([['d:m:y', 'D/M/Y']], dtype='<U5')

In [ ]:
np.char.equal(str1,str2)

array(False)

In [ ]:
char_name = 'hello sathvika here'

In [ ]:
np.char.replace(char_name,'there', 'sathvika')

array('hello swaraj swaraj', dtype='<U19')

In [ ]:
char_name

'hello swaraj there'

#Broadcasting


In [ ]:
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([10, 20, 30])     # Shape (3,)

# Broadcasting over multiple axes
result = arr1 * arr2
print(result)

[[10 20 30]
 [20 40 60]
 [30 60 90]]


In [ ]:
var = np.array([1,2,3])
print(var)

[1 2 3]


In [ ]:
var[1]

np.int64(2)

In [ ]:
index = [0,1]
var[index]

array([1, 2])